using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using Xunit;

namespace Slip39.Core.Tests;

/// <summary>
/// Recovers shares produced by a different SLIP-0039 implementation.
/// </summary>
/// <remarks>
/// <para>
/// The vectors in <c>interop-vectors.json</c> were generated by Trezor's <c>shamir-mnemonic</c>
/// (the reference Python implementation, PyPI 0.3.0), not by this library. They exist because
/// the specification's own test vectors all use the passphrase "TREZOR", so nothing in the suite
/// exercised what happens when no passphrase is given — and that is exactly where this library
/// diverged: it substituted "TREZOR" for no passphrase, making every share it produced by
/// default unreadable anywhere else. Not with an error. SLIP-0039 has no way to verify a
/// passphrase, so the other implementation returned a different secret and reported success.
/// </para>
/// <para>
/// Four of the six vectors therefore use no passphrase. A test that only round-trips through
/// this library cannot catch a divergence like that: both sides would be wrong in the same way.
/// </para>
/// </remarks>
public class InteropVectorTests
{
    public sealed record InteropVector(
        [property: JsonPropertyName("description")] string Description,
        [property: JsonPropertyName("passphrase")] string Passphrase,
        [property: JsonPropertyName("mnemonics")] string[] Mnemonics,
        [property: JsonPropertyName("masterSecret")] string MasterSecret);

    /// <summary>
    /// Reads the vectors that ship beside the test assembly.
    /// </summary>
    /// <remarks>
    /// <c>Path.Join</c> rather than <c>Path.Combine</c>: Combine discards everything before a
    /// rooted segment, which is never what a caller joining a directory to a file name wants.
    /// </remarks>
    private static List<InteropVector> LoadVectors()
    {
        var path = Path.Join(AppContext.BaseDirectory, "interop-vectors.json");
        return JsonSerializer.Deserialize<List<InteropVector>>(File.ReadAllText(path))!;
    }

    public static TheoryData<InteropVector> Vectors
    {
        get
        {
            var data = new TheoryData<InteropVector>();
            foreach (var vector in LoadVectors())
            {
                data.Add(vector);
            }

            return data;
        }
    }

    [Theory]
    [MemberData(nameof(Vectors))]
    public void ForeignShares_RecoverTheirOriginalSecret(InteropVector vector)
    {
        ArgumentNullException.ThrowIfNull(vector);

        var shares = vector.Mnemonics.Select(Slip39ShareParser.ParseFromMnemonic).ToList();

        // The passphrase is passed through as recorded: "" is a real value here, not a stand-in
        // for a default.
        var recovered = Slip39ShareCombination.CombineShares(shares, vector.Passphrase);

        Assert.Equal(vector.MasterSecret, Convert.ToHexString(recovered).ToLowerInvariant());
    }

    [Fact]
    public void ForeignShares_WithNoPassphrase_DoNotRecoverUnderTrezor()
    {
        // The specific regression, stated as its own test: reading a foreign no-passphrase
        // backup as though it had been made with "TREZOR" produces a different secret, and
        // nothing about the operation looks like a failure.
        var vector = LoadVectors().First(v => v.Passphrase.Length == 0);

        var shares = vector.Mnemonics.Select(Slip39ShareParser.ParseFromMnemonic).ToList();

        var underTrezor = Slip39ShareCombination.CombineShares(shares, "TREZOR");

        Assert.NotEqual(vector.MasterSecret, Convert.ToHexString(underTrezor).ToLowerInvariant());
    }

    [Theory]
    [MemberData(nameof(Vectors))]
    public void OurSharesForTheSameSecret_RoundTrip(InteropVector vector)
    {
        // Not an interoperability check on its own — it confirms that the shares this library
        // produces for the same secret and passphrase come back, so a failure above can be
        // attributed to the encoding rather than to the recovery path.
        ArgumentNullException.ThrowIfNull(vector);

        var secret = Convert.FromHexString(vector.MasterSecret);
        var configs = new List<Slip39ShareGeneration.GroupConfig> { new(2, 3) };

        var ours = Slip39ShareGeneration.GenerateShares(
            groupThreshold: 1, groupConfigs: configs, masterSecret: secret,
            passphrase: vector.Passphrase, iterationExponent: 0, isExtendable: false);

        var recovered = Slip39ShareCombination.CombineShares(ours.Take(2).ToList(), vector.Passphrase);

        Assert.Equal(secret, recovered);
    }
}
